language: python
python:
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.6
install:
  - npm install -g bower
  - pip install -q django-bower
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q djangorestframework
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
  - pip install -q
before_script:
  - psql -c 'create database heartdb;' -U postgres
script:
  - python manage.py test